name: Build Apache docker images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * SUN' # every sunday

jobs:

  build:
    name: Apache
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        apache_version: ['2.2', '2.4']

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ${{ matrix.apache_version }}
        repository: lephare/apache
        tags: ${{ matrix.apache_version }}
